"""authorid updated

Revision ID: af795c9a2cda
Revises: 6d940a3f5754
Create Date: 2025-02-21 11:52:51.908400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af795c9a2cda'
down_revision: Union[str, None] = '6d940a3f5754'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('no_of_books_published', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('author_id')
    )
    op.create_index(op.f('ix_authors_author_id'), 'authors', ['author_id'], unique=False)
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_books_author_id'), 'books', ['author_id'], unique=False)
    op.create_foreign_key(None, 'books', 'authors', ['author_id'], ['author_id'])
    op.drop_column('books', 'author')
    op.drop_column('books', 'year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('books', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_index(op.f('ix_books_author_id'), table_name='books')
    op.drop_column('books', 'author_id')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_author_id'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
